name: BuildPlugin
on:
    push:
        branches:
            - main

jobs:
    build:
        uses: FriendsOfShopware/actions/.github/workflows/github.yml@main
        with:
            extensionName: TinectMatomo
            shopwareVersion: 6.5.0
        secrets:
            ghToken: ${{ secrets.GITHUB_TOKEN }}
